# Generated by Django 4.0 on 2021-12-29 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flock_kirundi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sermon',
            new_name='KirundiSermon',
        ),
    ]
