# Generated by Django 4.0 on 2021-12-29 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flock_kirundi', '0002_rename_sermon_kirundisermon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='KirundiArticle',
        ),
        migrations.RenameModel(
            old_name='Event',
            new_name='KirundiEvent',
        ),
    ]
