# Generated by Django 4.0 on 2021-12-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flock_kirundi', '0003_rename_article_kirundiarticle_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='KirundiVideo',
        ),
        migrations.AlterField(
            model_name='kirundiarticle',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', upload_to='%Y/%m/%d/'),
        ),
    ]
