# Generated by Django 4.0 on 2021-12-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0002_rename_thumb_sermon_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', upload_to='%Y/%m/%d/'),
        ),
    ]
