# Generated by Django 4.0 on 2021-12-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0004_article_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=300)),
                ('in_progress', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=15)),
            ],
        ),
    ]
