# Generated by Django 4.0 on 2021-12-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0006_event_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField()),
            ],
        ),
    ]
