# Generated by Django 4.0 on 2021-12-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0008_delete_productkey_remove_event_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
