# Generated by Django 4.0 on 2021-12-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0009_event_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
    ]
