# Generated by Django 4.0 on 2021-12-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0010_remove_event_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
