# Generated by Django 4.0 on 2021-12-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0012_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
