# Generated by Django 4.0 on 2021-12-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0013_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d/'),
        ),
    ]
