# Generated by Django 4.0 on 2021-12-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0015_alter_article_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='profil.png', upload_to='%Y/%m/%d/')),
                ('full_Name', models.CharField(max_length=80)),
                ('service', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
            ],
        ),
    ]
