# Generated by Django 4.0 on 2021-12-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0016_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='full_Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='service',
            field=models.CharField(max_length=50),
        ),
    ]
