# Generated by Django 4.0 on 2021-12-31 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0019_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
