# Generated by Django 4.0 on 2021-12-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0020_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='profil.png', upload_to='%Y/%m/%d/')),
                ('full_Name', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_1', models.CharField(max_length=50)),
                ('phone_2', models.CharField(max_length=50)),
            ],
        ),
    ]
